# Generated by Django 5.1.7 on 2025-04-05 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_item_color_en_item_color_ru_item_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='category_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='items.category'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category', to='items.category'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Название категории'),
        ),
    ]
